---
apiVersion: v1
kind: Pod
metadata:
  name: hello-pod
  labels:
    name: hello-pod
spec:
  containers:
  - name: web-app
    image: nginx
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
      ports:
        - name: web
          containerPort: 80
          protocol: TCP 
    
